[metadata]
name = interfacemaster
version = attr: interfacemaster.__version__.__version__
description = A program of calculating interface structure
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Yaoshu Xie
author_email = ysxie@iis.u-tokyo.ac.jp
url = https://github.com/nmdl-mizo/interface_master
project_urls =
    Documentation = https://nmdl-mizo.github.io/interface_master/
    Repository = https://github.com/nmdl-mizo/interface_master
    Issues = https://github.com/nmdl-mizo/interface_master/issues
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Scientific/Engineering :: Chemistry
    Topic :: Scientific/Engineering :: Physics

[options]
python_requires = >= 3.8
packages = find:
install_requires = 
    pymatgen
    matplotlib
    numpy
    jobflow
    scikit-optimize
    tqdm
    gb_code

[options.extras_require]
dev =
    ipykernel
    sphinx
    pydata-sphinx-theme
    nbsphinx
    pytest
    pytest-cov