name: GitHub Pages

on:
#  push:
#    branches:
#      - master
#      - develop
  workflow_dispatch:
    inputs:
      deploy:
        required: true
        description: Deploy the html page on GitHub Pages
        default: false
#  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install package
        run: python3 -m pip install .

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Install sphinx
        run: python3 -m pip install -r ./.devcontainer/requirements.txt

      - name: Build sphinx html document
        run: sphinx-build docs docs/_build/

      - name: upload docs archive
        uses: actions/upload-artifact@v3
        with:
          name: docs_archive
          path: docs/_build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ inputs.deploy }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
